export const FETCH_ALL_BOARDS = "FETCH_ALL_BOARDS"
export const FETCH_ALL_BOARDS_COMPLETE = "FETCH_ALL_BOARDS_COMPLETE"
export const FETCH_ALL_BOARDS_FAIL = "FETCH_ALL_BOARDS_FAIL"

export const SAVE_DATE = "SAVE_DATE";
export const FETCH_LIST = "FETCH_LIST";
export const FETCH_LIST_COMPLETE = "FETCH_LIST_COMPLETE";
export const FETCH_LIST_FAILED="FETCH_LIST_FAILED";

export const FETCH_CARD_COMPLETE = 'FETCH_CARD_COMPLETE';
export const FETCH_BOARD_MEMBERS = 'FETCH_BOARD_MEMBERS';
export const FETCH_BOARD_MEMBERS_COMPLETE = 'FETCH_BOARD_MEMBERS_COMPLETE';
export const SET_FILTER ='SET_FILTER';
